name: degree-planner-development

services:
  workspace:
    container_name: degree-planner-development

    build:
      context: ..
      dockerfile: .devcontainer/dev.Dockerfile

    ports:
      - 3000:3000

    volumes:
      - ../:/workspace:rw
      - node_modules:/workspace/node_modules

    tty: true

volumes:
  node_modules: